import './globals.css';

export const metadata = { title: 'Local Net Worth Dashboard', description: 'Local-first private portfolio dashboard' };

const criticalDashboardCss = `
:root{--bg:#ffffff;--ink:#111827;--muted:#6b7280;--line:#e5e7eb;--blue:#2563eb;--green:#16a34a;--red:#dc2626;--blue-soft:#eef2ff;}
*{box-sizing:border-box;}
html{max-width:100%;overflow-x:clip;}
body{margin:0;max-width:100%;overflow-x:clip;background:var(--bg);color:var(--ink);font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;}
a{color:inherit;text-decoration:none;}
button,input,select{font:inherit;}
.app-shell{width:min(100%,1280px);margin:0 auto;padding:clamp(14px,2vw,24px) clamp(14px,2.7vw,32px) 56px;}
.topbar{position:sticky;top:0;z-index:10;display:grid;grid-template-columns:auto minmax(0,1fr) auto;align-items:center;gap:18px;width:100%;min-width:0;background:transparent;border:0;border-radius:0;padding:6px 0 26px;margin-bottom:4px;box-shadow:none;}
.brand{display:flex;align-items:center;gap:10px;font-weight:800;letter-spacing:-.02em;min-width:0;}.brand-mark{display:grid;place-items:center;width:34px;height:34px;flex:0 0 auto;border-radius:10px;background:#111827;color:white;font-weight:900;}
nav{display:flex;align-items:center;justify-content:center;gap:18px;flex-wrap:wrap;min-width:0;}nav a{color:#7a7f89;font-size:14px;font-weight:650;}nav a.active,nav a:hover{color:var(--ink);}.topbar-actions{display:flex;align-items:center;justify-content:flex-end;gap:10px;min-width:0;}.sync-pill,.ghost,.secondary-button,button{border:1px solid var(--line);background:#fff;border-radius:999px;padding:9px 13px;font-weight:750;color:#1f2937;cursor:pointer;box-shadow:none;}.sync-pill{display:flex;align-items:center;gap:8px;font-size:13px;white-space:nowrap;}.status-dot{display:inline-block;width:8px;height:8px;flex:0 0 auto;border-radius:99px;background:var(--green);}.avatar{display:grid;place-items:center;width:36px;height:36px;flex:0 0 auto;border-radius:50%;background:#111827;color:#fff;font-size:12px;font-weight:850;}
.dashboard-grid{display:grid;gap:22px;min-width:0;}.hero-grid{grid-template-columns:minmax(0,.94fr) minmax(0,1.16fr) minmax(0,1fr);align-items:start;}.panel,.card{min-width:0;background:transparent;border:0;border-radius:0;padding:0;box-shadow:none;}.eyebrow,.modal-section-title p{margin:0 0 10px;text-transform:uppercase;letter-spacing:.12em;font-size:12px;font-weight:850;color:#7b7f88;}.hero-metric{font-size:clamp(36px,3.4vw,52px);font-weight:850;line-height:.92;margin:4px 0 16px;letter-spacing:-.07em;white-space:nowrap;}.change-line{display:flex;align-items:center;gap:7px;font-size:16px;flex-wrap:wrap;}.positive{color:var(--green)!important;}.negative{color:var(--red)!important;}.muted{color:var(--muted);}.mini-metrics{display:flex;gap:18px;flex-wrap:wrap;margin:22px 0 0;color:#7b7f88;font-size:14px;}.mini-metrics strong{color:var(--green);}.primary{margin-top:18px;background:#111827;color:#fff;border-color:#111827;}.panel-title,.section-heading,.modal-section-title{display:flex;align-items:center;justify-content:space-between;gap:14px;flex-wrap:wrap;}.panel h2,.panel-title h2,.section-heading h2,.modal-header h2{margin:0;font-size:18px;letter-spacing:-.02em;}.chart-panel .panel-title h2{text-transform:uppercase;letter-spacing:.12em;font-size:12px;color:#7b7f88;}.range-tabs{display:flex;gap:5px;border-radius:999px;padding:3px;flex-wrap:wrap;}.range-tabs span{padding:6px 9px;border-radius:99px;color:#747780;font-size:12px;font-weight:750;}.range-tabs .selected{background:var(--blue-soft);color:#1d4ed8;}.trend-chart{width:100%;height:clamp(132px,18vw,184px);margin-top:12px;}.axis{display:flex;justify-content:space-between;color:var(--muted);font-size:12px;}.allocation-wrap{display:grid;grid-template-columns:132px minmax(0,1fr);gap:22px;align-items:center;}.donut{width:132px;height:132px;border-radius:50%;position:relative;}.donut:after{content:"";position:absolute;inset:28px;background:white;border-radius:50%;}.legend p{display:grid;grid-template-columns:auto minmax(0,1fr) auto;align-items:center;gap:8px;margin:10px 0;color:#4b5563;}.legend strong{font-weight:850;color:#111827;}.legend-dot{display:inline-block;width:10px;height:10px;border-radius:3px;background:var(--blue);}
.holdings-section{margin-top:32px;}.section-heading{margin-bottom:14px;}.section-heading h2{font-size:24px;}.section-heading p{margin:4px 0 0;color:var(--muted);}.button-row{display:flex;gap:10px;flex-wrap:wrap;}.holdings-card{background:#fff;border:1px solid var(--line);border-radius:28px;overflow:hidden;box-shadow:none;min-width:0;}.asset-group{border-top:1px solid var(--line);min-width:0;}.asset-group:first-child{border-top:0;}.asset-group summary{display:grid;grid-template-columns:minmax(0,1fr) auto;align-items:center;gap:12px;cursor:pointer;padding:18px 20px;font-weight:850;background:#fbfdff;}.asset-group summary span{display:flex;align-items:center;gap:8px;min-width:0;}.table-wrap{width:100%;max-width:100%;overflow-x:auto;}table{width:100%;border-collapse:collapse;min-width:760px;}th,td{text-align:left;border-top:1px solid var(--line);padding:13px 16px;white-space:nowrap;}th{text-transform:uppercase;letter-spacing:.08em;font-size:11px;color:#8b8f98;background:#fff;}
.modal-backdrop{position:fixed;inset:0;z-index:99;display:none;background:rgba(15,23,42,.45);backdrop-filter:blur(4px);padding:clamp(8px,3vw,28px);overflow:auto;}.modal-backdrop:target,.modal-backdrop:has(:target){display:flex;align-items:center;justify-content:center;}
@media(max-width:1100px){.topbar{grid-template-columns:1fr auto;}.topbar nav{grid-column:1/-1;order:3;justify-content:flex-start;}}
@media(max-width:900px){.hero-grid{grid-template-columns:1fr;}.topbar{align-items:start;}.modal-body{grid-template-columns:1fr;}.allocation-wrap{grid-template-columns:1fr;}.donut{margin:auto;}}
@media(max-width:620px){.app-shell{padding:12px;}.topbar{display:flex;flex-direction:column;align-items:stretch;padding-bottom:18px;}.topbar nav{justify-content:flex-start;gap:12px;}.topbar-actions{justify-content:space-between;flex-wrap:wrap;}nav a{font-size:13px;}.hero-metric{white-space:normal;font-size:clamp(40px,12vw,54px);}.sync-pill{white-space:normal;}}
`;

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return <html lang="en"><head><style data-critical-dashboard dangerouslySetInnerHTML={{ __html: criticalDashboardCss }} /></head><body>{children}</body></html>;
}
